import {
  AlertTriangle,
  ArrowRight,
  CalendarDays,
  Check,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  Eye,
  EyeOff,
  File,
  FileText,
  Framer,
  HelpCircle,
  Image,
  Laptop,
  Loader,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  Store,
  SunMedium,
  Ticket,
  Trash,
  Twitter,
  User,
  X,
  type Icon as LucideIcon,
  Home,
  ArrowUpIcon,
  ArrowDownIcon,
  DollarSign,
  Percent,
  PiggyBank,
  Landmark,
  Wallet,
  Pencil,
  CheckCircle2,
  RotateCcw
} from 'lucide-react'

import { FcGoogle } from 'react-icons/fc'

export type Icon = LucideIcon

export const Icons = {
  logo: Framer,
  eye: Eye,
  eyeOff: EyeOff,
  close: X,
  spinner: Loader,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  twitter: Twitter,
  check: Check,
  checkCircle: CheckCircle2,
  google: FcGoogle,
  events: CalendarDays,
  ticket: Ticket,
  club: Store,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  home: Home,
  income: ArrowUpIcon,
  outcome: ArrowDownIcon,
  money: DollarSign,
  percent: Percent,
  piggy: PiggyBank,
  bank: Landmark,
  wallet: Wallet,
  edit: Pencil,
  restart: RotateCcw
}
