import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  Eye,
  EyeOff,
  File,
  FileText,
  Framer,
  HelpCircle,
  Image,
  Loader,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  Trash,
  Twitter,
  User,
  X,
  CalendarDays,
  type Icon as LucideIcon
} from 'lucide-react'

import { FcGoogle } from 'react-icons/fc'

export type Icon = LucideIcon

export const Icons = {
  logo: Framer,
  eye: Eye,
  eyeOff: EyeOff,
  close: X,
  spinner: Loader,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  twitter: Twitter,
  check: Check,
  google: FcGoogle,
  events: CalendarDays,
}
